### PR TITLE
Update +page.svelte

### PR DESCRIPTION
**Pull request by VoiceOfSoftware**
Fixed typo in GradientHeading direction

## Before submitting the PR:
- [ ] Does your PR reference an issue? If not, please [chat to the team on Discord](https://discord.gg/EXqV7W8MtY) or [GitHub](https://github.com/Brain-Bones/skeleton/discussions) before submission.
- [ ] Did you update and run tests before submission using `npm run test`?
- [ ] Does your branch follow our [naming convention](https://www.skeleton.dev/docs/contributions)? If not, please amend the branch name using `branch -m new-branch-name`
- [ ] Did you update documentation related to your new feature or changes?

## What does your PR address?

Please briefly describe your changes here.

### Tips
- Tap "convert to draft" to indicate this is work in progress.
- Link to an issue using the verbiage [Fixes #XX](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- Linked issues will auto-close when the PR is merged.

### CODE REVIEW

**Comment by endigo9740** [comment]
@VoiceOfSoftware Hey, thanks for the PR, but unfortunately this is not a mistake. The value of `bg-gradient-to-br` is a valid Tailwind utility class:

https://tailwindcss.com/docs/background-image#linear-gradients

Screen Shot 2022-11-18 at 10 23 12 AM

It creates a gradient at slopes to the bottom-right corner (br).

**Comment by VoiceOfSoftware** [comment]
Sorry, I assumed that because it does not render in either Safari or Chrome, that it was a typo. I followed the getting started guide, and that <h1> renders white, same as the page background color

**Comment by VoiceOfSoftware** [comment]
Pasted_Image_11_18_22__6_42_PM

**Comment by endigo9740** [comment]
@VoiceOfSoftware Hmm sounds like a bug somewhere. Can you verify if the gradient displays for you on our docs page:
https://www.skeleton.dev/components/gradient-headings

There is a `br` option in the settings on the right side. I've tested in both Chrome and Safari and it's showing there.

**Comment by VoiceOfSoftware** [comment]
It does render correctly in all its forms on the docs page. Not sure why it's not rendering when I build my own app from the getting started guide, specifically after following the instructions at the bottom of this page https://www.skeleton.dev/guides/frameworks/sveltekit -- do I need to install another package?

**Comment by endigo9740** [comment]
@VoiceOfSoftware I'd assume you imported the package in your script tag, correct? 

```ts
<script>
    import { GradientHeading } from '@brainandbones/skeleton';
</script>
```

If so everything else should be fine. I'm away from my workstation today but I'll see if I can get someone else to test and confirm your results. Sorry for the trouble!

**Comment by endigo9740** [comment]
FYI I made a post in the #support channel on Discord if you wish to follow along.

**Pull request closed without merging**
