### PR TITLE
Docs/fix-fileDropzone-typo

### LINKED ISSUE #468: FileDropzone default text information is plural
### Current Behavior

`FileDropzone` is in single file mode by default.
But the information text is
> Drop files or click to select

This would be better
> Drop a file or click to select

And after enabling multiple file mode,
> Drop files or click to select

### Steps To Reproduce

```
<FileDropzone />
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ryceg**
## Before submitting the PR:
- [x] Does your PR reference an issue? If not, please [chat to the team on Discord](https://discord.gg/EXqV7W8MtY) or [GitHub](https://github.com/Brain-Bones/skeleton/discussions) before submission.
- [x] Did you you update and run tests before submission using `npm run test`?
- [x] Does your branch follow our [naming convention](https://skeleton.brainandbonesllc.com/docs/contributions)? If not, please amend the branch name using `branch -m new-branch-name`
- [x] Did you update documentation related to your new feature or changes?

## What does your PR address?

Implements @leranjun's suggested fix, and closes #468

### CODE REVIEW

**Comment by endigo9740** [comment]
@ryceg This seems to bundle in a bunch of changes to the Sveld Mapper. Not sure if you intended to include those in this.

**Comment by ryceg** [comment]
Aww balls I thought I removed those 😖

**Comment by leranjun** [comment]
I think you might need to drop the unrelated commits so that it matches `dev` :p

Btw, copying my original comment over here:

> `$$restProps` seems to be [generally not recommended](https://svelte.dev/docs#template-syntax-attributes-and-props) due to optimisation issues. Could we consider just exporting `multiple` plainly instead?

**Comment by endigo9740** [comment]
@leranjun I'm aware of Svelte's stance on restProps. We basically only use it for input-related inputs due to the large number possible attributes required. It's not just about multiple, but also id, name, required, etc. It's like a cat and mouse game. I don't like using it, but I also don't want to research every possible input proper out there per each use case. This is one reason we generally try to avoid input components.

**Comment by endigo9740** [comment]
@ryceg Ping me when this is fixed and I'll merge right away!

**Pull request closed without merging**
