### PR TITLE
Feat/add blog section

### PR DESCRIPTION
**Pull request by niktek**
NOT FOR MERGING - had to make this a proper pull request as I wanted to see the PR deploy to Vercel.  There is a 500 error on trying to read an actual blog article - does anything show on the Vercel error logs ?? Because of course it works fine locally...

Couple of other issues arising:

Need to have better control of the sidebar.

Adding TW Typography works, but there are some theme considerations that have to be taken into account - probably as a customised Typography override that utilises the theme tokens.

### CODE REVIEW

**Comment by niktek** [comment]
There is also a 500 error on trying to read an actual blog article - does anything show on the Vercel error logs ??  Because of course it works fine locally...

**Comment by endigo9740** [comment]
@niktek I kind of backtracked on the Typography plugin. I think I'd rather us handle those styles ourselves, either as as part of our lib stylesheets or custom styles for things that re unique for us.

Here's a dump of the "function logs". Hopefully that's what you need:

```
[GET] /components/range-sliders
09:22:49:94
2022-11-04T14:22:49.990Z	c5ae65ed-b7cf-4c7f-967c-fb584611f6f1	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: fetch failed","reason":{"errorType":"TypeError","errorMessage":"fetch failed","cause":{"errorType":"Error","errorMessage":"Client network socket disconnected before secure TLS connection was established","code":"ECONNRESET","host":"jsonplaceholder.typicode.com","port":443,"stack":["Error: Client network socket disconnected before secure TLS connection was established","    at connResetException (node:internal/errors:692:14)","    at TLSSocket.onConnectEnd (node:_tls_wrap:1587:19)","    at TLSSocket.emit (node:events:539:35)","    at endReadableNT (node:internal/streams/readable:1345:12)","    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]},"stack":["TypeError: fetch failed","    at fetch (/var/task/node_modules/undici/index.js:105:13)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async getTableSource (file:///var/task/.svelte-kit/output/server/entries/pages/(inner)/components/data-tables/_page.svelte.js:122:18)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: fetch failed","    at process.<anonymous> (file:///var/runtime/index.mjs:1131:17)","    at process.emit (node:events:539:35)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
[ERROR] [1667571770008] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 400.
RequestId: 5ebbf985-04c8-4da6-86c0-0851a4406616 Error: Runtime exited with error: exit status 128
Runtime.ExitError
[GET] /robots.txt
11:25:37:95
2022-11-03T16:25:38.029Z	bcbdc829-2d5c-4942-8527-30be15893a41	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: fetch failed","reason":{"errorType":"TypeError","errorMessage":"fetch failed","cause":{"errorType":"Error","errorMessage":"Client network socket disconnected before secure TLS connection was established","code":"ECONNRESET","host":"jsonplaceholder.typicode.com","port":443,"stack":["Error: Client network socket disconnected before secure TLS connection was established","    at connResetException (node:internal/errors:692:14)","    at TLSSocket.onConnectEnd (node:_tls_wrap:1587:19)","    at TLSSocket.emit (node:events:539:35)","    at endReadableNT (node:internal/streams/readable:1345:12)","    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]},"stack":["TypeError: fetch failed","    at fetch (/var/task/node_modules/undici/index.js:105:13)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async getTableSource (file:///var/task/.svelte-kit/output/server/entries/pages/(inner)/components/data-tables/_page.svelte.js:122:18)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: fetch failed","    at process.<anonymous> (file:///var/runtime/index.mjs:1131:17)","    at process.emit (node:events:539:35)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
RequestId: 7e8a3e76-544d-4f33-9535-a38e642646e0 Error: Runtime exited with error: signal: segmentation fault
Runtime.ExitError
[GET] /robots.txt
10:21:55:00
2022-11-03T15:21:55.075Z	841e3481-1dd3-4d31-948c-b007c6fd101b	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: fetch failed","reason":{"errorType":"TypeError","errorMessage":"fetch failed","cause":{"errorType":"SocketError","errorMessage":"other side closed","code":"UND_ERR_SOCKET","name":"SocketError","socket":{"localAddress":"169.254.76.1","localPort":59510,"remoteAddress":"172.67.155.76","remotePort":443,"remoteFamily":"IPv4","bytesWritten":201,"bytesRead":0},"stack":["SocketError: other side closed","    at TLSSocket.onSocketEnd (/var/task/node_modules/undici/lib/client.js:958:22)","    at TLSSocket.emit (node:events:539:35)","    at endReadableNT (node:internal/streams/readable:1345:12)","    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]},"stack":["TypeError: fetch failed","    at fetch (/var/task/node_modules/undici/index.js:105:13)","    at async getTableSource (file:///var/task/.svelte-kit/output/server/entries/pages/(inner)/components/data-tables/_page.svelte.js:122:18)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: fetch failed","    at process.<anonymous> (file:///var/runtime/index.mjs:1131:17)","    at process.emit (node:events:539:35)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
Unknown application error occurred
[GET] /
06:38:23:77
2022-11-03T11:38:23.793Z	fbdcfa21-2956-469b-9bd0-a8f1e16f960a	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: fetch failed","reason":{"errorType":"TypeError","errorMessage":"fetch failed","cause":{"errorType":"Error","errorMessage":"Client network socket disconnected before secure TLS connection was established","code":"ECONNRESET","host":"jsonplaceholder.typicode.com","port":443,"stack":["Error: Client network socket disconnected before secure TLS connection was established","    at connResetException (node:internal/errors:692:14)","    at TLSSocket.onConnectEnd (node:_tls_wrap:1587:19)","    at TLSSocket.emit (node:events:539:35)","    at endReadableNT (node:internal/streams/readable:1345:12)","    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]},"stack":["TypeError: fetch failed","    at fetch (/var/task/node_modules/undici/index.js:105:13)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async getTableSource (file:///var/task/.svelte-kit/output/server/entries/pages/(inner)/components/data-tables/_page.svelte.js:122:18)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: fetch failed","    at process.<anonymous> (file:///var/runtime/index.mjs:1131:17)","    at process.emit (node:events:539:35)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
[ERROR] [1667475503794] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 400.
RequestId: bd18fe5b-5496-408f-9e83-274dc8c04c9c Error: Runtime exited with error: exit status 128
Runtime.ExitError
[GET] /components/slide-toggles
04:23:10:00
2022-11-03T09:23:10.053Z	1b82634c-2ed7-4b45-b275-f6463943ec5b	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: fetch failed","reason":{"errorType":"TypeError","errorMessage":"fetch failed","cause":{"errorType":"Error","errorMessage":"Client network socket disconnected before secure TLS connection was established","code":"ECONNRESET","host":"jsonplaceholder.typicode.com","port":443,"stack":["Error: Client network socket disconnected before secure TLS connection was established","    at connResetException (node:internal/errors:692:14)","    at TLSSocket.onConnectEnd (node:_tls_wrap:1587:19)","    at TLSSocket.emit (node:events:539:35)","    at endReadableNT (node:internal/streams/readable:1345:12)","    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]},"stack":["TypeError: fetch failed","    at fetch (/var/task/node_modules/undici/index.js:105:13)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async getTableSource (file:///var/task/.svelte-kit/output/server/entries/pages/(inner)/components/data-tables/_page.svelte.js:122:18)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: fetch failed","    at process.<anonymous> (file:///var/runtime/index.mjs:1131:17)","    at process.emit (node:events:539:35)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
[ERROR] [1667467390054] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 400.
RequestId: 0c9a85dd-5276-475f-b912-97908136fdfe Error: Runtime exited with error: exit status 128
Runtime.ExitError
[GET] /components/dividers
23:59:13:59
2022-11-03T04:59:13.726Z	bc0ddae5-f8d0-425e-b1c8-a2629464f524	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: fetch failed","reason":{"errorType":"TypeError","errorMessage":"fetch failed","cause":{"errorType":"ConnectTimeoutError","errorMessage":"Connect Timeout Error","code":"UND_ERR_CONNECT_TIMEOUT","name":"ConnectTimeoutError","message":"Connect Timeout Error","stack":["ConnectTimeoutError: Connect Timeout Error","    at onConnectTimeout (/var/task/node_modules/undici/lib/core/connect.js:131:24)","    at /var/task/node_modules/undici/lib/core/connect.js:78:46","    at Immediate._onImmediate (/var/task/node_modules/undici/lib/core/connect.js:119:9)","    at processImmediate (node:internal/timers:466:21)"]},"stack":["TypeError: fetch failed","    at fetch (/var/task/node_modules/undici/index.js:105:13)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async getTableSource (file:///var/task/.svelte-kit/output/server/entries/pages/(inner)/components/data-tables/_page.svelte.js:122:18)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: fetch failed","    at process.<anonymous> (file:///var/runtime/index.mjs:1131:17)","    at process.emit (node:events:539:35)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
[ERROR] [1667451553727] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 400.
RequestId: 77d06a78-c777-4da5-93c9-a042964b0c63 Error: Runtime exited with error: exit status 128
Runtime.ExitError
[GET] /guides/styling
20:17:48:27
2022-11-03T01:17:48.327Z	ee6f6eb5-e352-48e4-808a-e784c17aee8b	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: fetch failed","reason":{"errorType":"TypeError","errorMessage":"fetch failed","cause":{"errorType":"Error","errorMessage":"Client network socket disconnected before secure TLS connection was established","code":"ECONNRESET","host":"jsonplaceholder.typicode.com","port":443,"stack":["Error: Client network socket disconnected before secure TLS connection was established","    at connResetException (node:internal/errors:692:14)","    at TLSSocket.onConnectEnd (node:_tls_wrap:1587:19)","    at TLSSocket.emit (node:events:539:35)","    at endReadableNT (node:internal/streams/readable:1345:12)","    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]},"stack":["TypeError: fetch failed","    at fetch (/var/task/node_modules/undici/index.js:105:13)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async getTableSource (file:///var/task/.svelte-kit/output/server/entries/pages/(inner)/components/data-tables/_page.svelte.js:122:18)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: fetch failed","    at process.<anonymous> (file:///var/runtime/index.mjs:1131:17)","    at process.emit (node:events:539:35)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
[ERROR] [1667438268328] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 400.
RequestId: 86c9d53f-4608-4e04-9e28-7d1e961624d6 Error: Runtime exited with error: exit status 128
Runtime.ExitError
[GET] /components/slide-toggles
19:22:59:06
2022-11-03T00:22:59.119Z	5265b796-7a2f-4f68-aa01-b05b4bf4337f	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: fetch failed","reason":{"errorType":"TypeError","errorMessage":"fetch failed","cause":{"errorType":"Error","errorMessage":"Client network socket disconnected before secure TLS connection was established","code":"ECONNRESET","host":"jsonplaceholder.typicode.com","port":443,"stack":["Error: Client network socket disconnected before secure TLS connection was established","    at connResetException (node:internal/errors:692:14)","    at TLSSocket.onConnectEnd (node:_tls_wrap:1587:19)","    at TLSSocket.emit (node:events:539:35)","    at endReadableNT (node:internal/streams/readable:1345:12)","    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]},"stack":["TypeError: fetch failed","    at fetch (/var/task/node_modules/undici/index.js:105:13)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async getTableSource (file:///var/task/.svelte-kit/output/server/entries/pages/(inner)/components/data-tables/_page.svelte.js:122:18)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: fetch failed","    at process.<anonymous> (file:///var/runtime/index.mjs:1131:17)","    at process.emit (node:events:539:35)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
Unknown application error occurred
[GET] /
17:08:17:26
2022-11-02T22:08:17.324Z	4ba781b0-06db-42fc-8281-80780090ef0f	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: fetch failed","reason":{"errorType":"TypeError","errorMessage":"fetch failed","cause":{"errorType":"SocketError","errorMessage":"other side closed","code":"UND_ERR_SOCKET","name":"SocketError","socket":{"localAddress":"169.254.76.1","localPort":58906,"remoteAddress":"104.21.58.30","remotePort":443,"remoteFamily":"IPv4","bytesWritten":201,"bytesRead":0},"stack":["SocketError: other side closed","    at TLSSocket.onSocketEnd (/var/task/node_modules/undici/lib/client.js:958:22)","    at TLSSocket.emit (node:events:539:35)","    at endReadableNT (node:internal/streams/readable:1345:12)","    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]},"stack":["TypeError: fetch failed","    at fetch (/var/task/node_modules/undici/index.js:105:13)","    at async getTableSource (file:///var/task/.svelte-kit/output/server/entries/pages/(inner)/components/data-tables/_page.svelte.js:122:18)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: fetch failed","    at process.<anonymous> (file:///var/runtime/index.mjs:1131:17)","    at process.emit (node:events:539:35)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
[ERROR] [1667426897328] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 400.
RequestId: 83b7ce38-edfc-46f7-85ea-58cead0612c9 Error: Runtime exited with error: exit status 128
Runtime.ExitError
[GET] /guides/install
13:09:51:74
2022-11-02T18:09:51.765Z	a9d4d7bf-3b9b-42f4-9772-8482c78a220e	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: fetch failed","reason":{"errorType":"TypeError","errorMessage":"fetch failed","cause":{"errorType":"Error","errorMessage":"Client network socket disconnected before secure TLS connection was established","code":"ECONNRESET","host":"jsonplaceholder.typicode.com","port":443,"stack":["Error: Client network socket disconnected before secure TLS connection was established","    at connResetException (node:internal/errors:692:14)","    at TLSSocket.onConnectEnd (node:_tls_wrap:1587:19)","    at TLSSocket.emit (node:events:539:35)","    at endReadableNT (node:internal/streams/readable:1345:12)","    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]},"stack":["TypeError: fetch failed","    at fetch (/var/task/node_modules/undici/index.js:105:13)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async getTableSource (file:///var/task/.svelte-kit/output/server/entries/pages/(inner)/components/data-tables/_page.svelte.js:122:18)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: fetch failed","    at process.<anonymous> (file:///var/runtime/index.mjs:1131:17)","    at process.emit (node:events:539:35)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
[ERROR] [1667412591766] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 400.
RequestId: 0b8a73f6-1756-4d4e-aa22-3ef10f8d6a44 Error: Runtime exited with error: exit status 128
Runtime.ExitError
[GET] /wp-login.php
13:01:23:25
2022-11-02T18:01:23.312Z	57a2b403-3c82-4683-ba5f-9c496ab695e0	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: fetch failed","reason":{"errorType":"TypeError","errorMessage":"fetch failed","cause":{"errorType":"SocketError","errorMessage":"other side closed","code":"UND_ERR_SOCKET","name":"SocketError","socket":{"localAddress":"169.254.76.1","localPort":33368,"remoteAddress":"172.67.155.76","remotePort":443,"remoteFamily":"IPv4","bytesWritten":201,"bytesRead":0},"stack":["SocketError: other side closed","    at TLSSocket.onSocketEnd (/var/task/node_modules/undici/lib/client.js:958:22)","    at TLSSocket.emit (node:events:539:35)","    at endReadableNT (node:internal/streams/readable:1345:12)","    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]},"stack":["TypeError: fetch failed","    at fetch (/var/task/node_modules/undici/index.js:105:13)","    at async getTableSource (file:///var/task/.svelte-kit/output/server/entries/pages/(inner)/components/data-tables/_page.svelte.js:122:18)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: fetch failed","    at process.<anonymous> (file:///var/runtime/index.mjs:1131:17)","    at process.emit (node:events:539:35)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
Unknown application error occurred
[GET] /
12:36:42:91
2022-11-02T17:36:42.984Z	c87502b8-1dc5-4fed-bc42-494ef6ba9bb9	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: fetch failed","reason":{"errorType":"TypeError","errorMessage":"fetch failed","cause":{"errorType":"Error","errorMessage":"Client network socket disconnected before secure TLS connection was established","code":"ECONNRESET","host":"jsonplaceholder.typicode.com","port":443,"stack":["Error: Client network socket disconnected before secure TLS connection was established","    at connResetException (node:internal/errors:692:14)","    at TLSSocket.onConnectEnd (node:_tls_wrap:1587:19)","    at TLSSocket.emit (node:events:539:35)","    at endReadableNT (node:internal/streams/readable:1345:12)","    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]},"stack":["TypeError: fetch failed","    at fetch (/var/task/node_modules/undici/index.js:105:13)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async getTableSource (file:///var/task/.svelte-kit/output/server/entries/pages/(inner)/components/data-tables/_page.svelte.js:122:18)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: fetch failed","    at process.<anonymous> (file:///var/runtime/index.mjs:1131:17)","    at process.emit (node:events:539:35)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
Unknown application error occurred
[GET] /
10:31:09:92
2022-11-02T15:31:09.953Z	837c8c6d-fb9b-46f0-b821-56c2d789cf2c	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: fetch failed","reason":{"errorType":"TypeError","errorMessage":"fetch failed","cause":{"errorType":"Error","errorMessage":"Client network socket disconnected before secure TLS connection was established","code":"ECONNRESET","host":"jsonplaceholder.typicode.com","port":443,"stack":["Error: Client network socket disconnected before secure TLS connection was established","    at connResetException (node:internal/errors:692:14)","    at TLSSocket.onConnectEnd (node:_tls_wrap:1587:19)","    at TLSSocket.emit (node:events:539:35)","    at endReadableNT (node:internal/streams/readable:1345:12)","    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]},"stack":["TypeError: fetch failed","    at fetch (/var/task/node_modules/undici/index.js:105:13)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async getTableSource (file:///var/task/.svelte-kit/output/server/entries/pages/(inner)/components/data-tables/_page.svelte.js:122:18)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: fetch failed","    at process.<anonymous> (file:///var/runtime/index.mjs:1131:17)","    at process.emit (node:events:539:35)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
[ERROR] [1667403069954] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 400.
RequestId: fa021a1a-6427-46e3-966d-78aadb35b639 Error: Runtime exited with error: exit status 128
Runtime.ExitError
[GET] /utilities/tooltips
10:20:02:55
2022-11-02T15:20:02.688Z	e2b39ca4-e0d4-49b5-9718-40817936a4bc	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: fetch failed","reason":{"errorType":"TypeError","errorMessage":"fetch failed","cause":{"errorType":"Error","errorMessage":"Client network socket disconnected before secure TLS connection was established","code":"ECONNRESET","host":"jsonplaceholder.typicode.com","port":443,"stack":["Error: Client network socket disconnected before secure TLS connection was established","    at connResetException (node:internal/errors:692:14)","    at TLSSocket.onConnectEnd (node:_tls_wrap:1587:19)","    at TLSSocket.emit (node:events:539:35)","    at endReadableNT (node:internal/streams/readable:1345:12)","    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]},"stack":["TypeError: fetch failed","    at fetch (/var/task/node_modules/undici/index.js:105:13)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async getTableSource (file:///var/task/.svelte-kit/output/server/entries/pages/(inner)/components/data-tables/_page.svelte.js:122:18)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: fetch failed","    at process.<anonymous> (file:///var/runtime/index.mjs:1131:17)","    at process.emit (node:events:539:35)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
[ERROR] [1667402402689] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 400.
RequestId: e64ebb00-d133-4e3c-99c9-6b191ef32d4f Error: Runtime exited with error: exit status 128
Runtime.ExitError
[GET] /tailwind
08:49:12:46
2022-11-02T13:49:12.593Z	da65f7fe-fd90-45f3-89ba-8785bba76ee6	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: fetch failed","reason":{"errorType":"TypeError","errorMessage":"fetch failed","cause":{"errorType":"ConnectTimeoutError","errorMessage":"Connect Timeout Error","code":"UND_ERR_CONNECT_TIMEOUT","name":"ConnectTimeoutError","message":"Connect Timeout Error","stack":["ConnectTimeoutError: Connect Timeout Error","    at onConnectTimeout (/var/task/node_modules/undici/lib/core/connect.js:131:24)","    at /var/task/node_modules/undici/lib/core/connect.js:78:46","    at Immediate._onImmediate (/var/task/node_modules/undici/lib/core/connect.js:119:9)","    at processImmediate (node:internal/timers:466:21)"]},"stack":["TypeError: fetch failed","    at fetch (/var/task/node_modules/undici/index.js:105:13)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async getTableSource (file:///var/task/.svelte-kit/output/server/entries/pages/(inner)/components/data-tables/_page.svelte.js:122:18)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: fetch failed","    at process.<anonymous> (file:///var/runtime/index.mjs:1131:17)","    at process.emit (node:events:539:35)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
RequestId: d8162f48-edfc-49bc-b246-c18a87a4586b Error: Runtime exited with error: signal: segmentation fault
Runtime.ExitError
[GET] /_app/immutable/chunks/3-f6740376.js
05:39:26:76
2022-11-02T10:39:27.057Z	6f7060f4-d1d0-4bc8-893e-a70e9d6a69a6	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: fetch failed","reason":{"errorType":"TypeError","errorMessage":"fetch failed","cause":{"errorType":"Error","errorMessage":"Client network socket disconnected before secure TLS connection was established","code":"ECONNRESET","host":"jsonplaceholder.typicode.com","port":443,"stack":["Error: Client network socket disconnected before secure TLS connection was established","    at connResetException (node:internal/errors:692:14)","    at TLSSocket.onConnectEnd (node:_tls_wrap:1587:19)","    at TLSSocket.emit (node:events:539:35)","    at endReadableNT (node:internal/streams/readable:1345:12)","    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]},"stack":["TypeError: fetch failed","    at fetch (/var/task/node_modules/undici/index.js:105:13)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async getTableSource (file:///var/task/.svelte-kit/output/server/entries/pages/(inner)/components/data-tables/_page.svelte.js:122:18)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: fetch failed","    at process.<anonymous> (file:///var/runtime/index.mjs:1131:17)","    at process.emit (node:events:539:35)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
RequestId: 5c9ef203-c65a-4606-8008-7294ac4bef84 Error: Runtime exited with error: signal: segmentation fault
Runtime.ExitError
[GET] /
04:34:04:46
2022-11-02T09:34:04.540Z	a0ead78b-4288-42f5-9274-11b2598be37a	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: fetch failed","reason":{"errorType":"TypeError","errorMessage":"fetch failed","cause":{"errorType":"Error","errorMessage":"Client network socket disconnected before secure TLS connection was established","code":"ECONNRESET","host":"jsonplaceholder.typicode.com","port":443,"stack":["Error: Client network socket disconnected before secure TLS connection was established","    at connResetException (node:internal/errors:692:14)","    at TLSSocket.onConnectEnd (node:_tls_wrap:1587:19)","    at TLSSocket.emit (node:events:539:35)","    at endReadableNT (node:internal/streams/readable:1345:12)","    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]},"stack":["TypeError: fetch failed","    at fetch (/var/task/node_modules/undici/index.js:105:13)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async getTableSource (file:///var/task/.svelte-kit/output/server/entries/pages/(inner)/components/data-tables/_page.svelte.js:122:18)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: fetch failed","    at process.<anonymous> (file:///var/runtime/index.mjs:1131:17)","    at process.emit (node:events:539:35)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
[ERROR] [1667381644541] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 400.
RequestId: 9cb54af3-d644-4ab3-a086-00001f473fb4 Error: Runtime exited with error: exit status 128
Runtime.ExitError
[GET] /components/accordions
20:19:15:44
2022-11-02T01:19:15.471Z	60677b76-519f-49fb-bea0-385957110363	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: fetch failed","reason":{"errorType":"TypeError","errorMessage":"fetch failed","cause":{"errorType":"SocketError","errorMessage":"other side closed","code":"UND_ERR_SOCKET","name":"SocketError","socket":{"localAddress":"169.254.76.1","localPort":57636,"remoteAddress":"172.67.155.76","remotePort":443,"remoteFamily":"IPv4","bytesWritten":201,"bytesRead":0},"stack":["SocketError: other side closed","    at TLSSocket.onSocketEnd (/var/task/node_modules/undici/lib/client.js:958:22)","    at TLSSocket.emit (node:events:539:35)","    at endReadableNT (node:internal/streams/readable:1345:12)","    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]},"stack":["TypeError: fetch failed","    at fetch (/var/task/node_modules/undici/index.js:105:13)","    at async getTableSource (file:///var/task/.svelte-kit/output/server/entries/pages/(inner)/components/data-tables/_page.svelte.js:122:18)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: fetch failed","    at process.<anonymous> (file:///var/runtime/index.mjs:1131:17)","    at process.emit (node:events:539:35)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
Unknown application error occurred
```

**Comment by niktek** [comment]
It's at least 'working' now by forcing a `data-svelte-refresh` on the links leading back to the listing.  Which of course causes a flash to default theme before reloading the user selected theme.  This branch has the settings for forcing prerender on and uses adapter static.  I'd be curious to see if it has resulted in a speed up in performance from the other side of the world: https://vercel.com/niktek/skeleton/83XMy5zMWM2gYnu82z9WT9xc1rtb is on my Sydney instance.

**Comment by endigo9740** [comment]
Per discussion with Nik in Discord, I'm closing this in favor of the ghost blog PR branch.

**Pull request closed without merging**
