### PR TITLE
File Button Component

### PR DESCRIPTION
**Pull request by salisshuaibu11**

### CODE REVIEW

**Comment by endigo9740** [comment]
@salisshuaibu11 I've converted this a draft. Just tap "ready for review" when you're ready for me to go through it for a proper review. Thanks!

**Comment by endigo9740** [comment]
@salisshuaibu11 I've finished my review and made some minor changes. Mostly just prepping the for the rest of the documentation, which I'll let you handle.

Key changes:

- Seems we should bind to `file` not `value` for this, so good catch there!
- When you select an image with the picker it'll how show some basic details in the UI in a `<pre>` tag
- Likewise the onSelect method will log the full data to the console
- I've made a few layout/cosmetic changes.

Just go ahead and document the Usage, Props, and single Slot (default). When that's done I'll add the test spec and merge!

This was a challenging one, using stuff I haven't touched in Svelte yet either! So great job 👍

**Comment by endigo9740** [comment]
@salisshuaibu11 FYI I've set this back into the Draft state until the changes above are complete. Tap "ready for review" when your ready for me to take another look please!

**Comment by salisshuaibu11** [comment]
@endigo9740 yeah , you can go ahead, thank you

**Comment by endigo9740** [comment]
@salisshuaibu11 I mentioned the documentation needs to be flushed out for this one before I review again. I don't see any additional commits adding this. If you could please add that information please. I'll review and add the test specs once that's provided. Thanks!

**Comment by salisshuaibu11** [comment]
Oh yeah, let me do that, sorry

**Comment by endigo9740** [comment]
I made a few modifications:

- Added the test spect
- Updated the use to show the minimum properties, plus an example of binded data
- Adjusted the wording of the props docs slightly, added a link to the file accepts values
- Documented the `on:change` event

I think with that we're good, so merging now. Thanks for another great contribution Salisu!

**Pull request merged**
