### PR TITLE
Placeholder component

### PR DESCRIPTION
**Pull request by salisshuaibu11**

### CODE REVIEW

**Comment by endigo9740** [comment]
Finally had a moment to sit down and review this @salisshuaibu11. This is really great! Very cleanly done and implemented! I especially appreciate the fact you took the time to create the documentation page and add the component to the `index.ts` file for the package export.

There's a few minor stylistic things that I may look to adjust on my end Things that are easy to show than tell. But once the changes are made I'll notify you here so you can pull down and review them directly as well.

That said, the only major gap that we're missing a test cases for this new component. If you're not familiar with testing, then I have a video I can share. I saw down with Nik and Luke last week and explained the whole process here. It's a big long (about an hour and half), but should cover everything you need to know to get started:
https://www.youtube.com/watch?v=Ru3FtSzN128

If you wish to add the test yourself, just let me know. Otherwise I don't mind adding it alongside the other updates mentioned above. Either way great job and I really appreciate the help! Excited to get this one merged soon!

**Comment by salisshuaibu11** [comment]
Thank you @endigo9740 You can go ahead and write the test alongside the other updates while I continue to watch the testing video, I started watching I guess the day before yesterday, just that I didn't finish.

**Comment by endigo9740** [comment]
Hey @salisshuaibu11 I've gone ahead and committed my changes. See the commit tab here on the PR section to review my changes, or view directly here:
https://github.com/Brain-Bones/skeleton/pull/219/commits/61a8fc7b21f00310e9c0b7b8088e8d842f2e8eb6

Like I mentioned, not a ton of changes. But here's what was updated:

- I added the new test spec, per our prior discussion

### Doc:

- Updated the information for on the documentation to use similar language to our other components
- Modified the example layout styles just a bit. Was able to simplify and streamline a bit (note we aim for `-4` (REM) for spacing elements)

## Components

- We allow the documentation page to document what each prop does, no need to duplicate that in the code
- I created a `background` prop in case users want to override this. Likewise I added a light/dark mode version of the background - you only had the base! (NOTE: this will updated in the Docs in a second commit)
- I renamed a prop `radius` to `rounded` to keep it inline with other component conventions
- I modified the `classesRadius` reactive property to better handle the toggle between square and circle.
- By adding `aspect square` only the `circle` and `width` props are needed for circles now. No height needed!
- I updated `classesAnimate` to have an empty string if animate is not enabled. Any other value would show in the class attribute values in the template!
- I dropped the extra wrapping `div` element. Everything is handled on the one single div now.
- Added a `placeholder` class in the div classes. We use this in place of an ID, since IDs must be unique on the page, but users could have multiple instances of this component on their page.
- Finally I added a fallback in case the `$$props.classs` is not in use like so: `${$$props.class || ''}` Otherwise it'll show the word "undefined" in the list of classes

Let me know if you have any questions about these changes, but otherwise I'll look to get merged if you approve these changes!

**Comment by salisshuaibu11** [comment]
Don't have any questions, this looks clean.

**Comment by endigo9740** [comment]
Ok great. This has been merged!

You should appear on the list of contributors both in the repo and on the homepage of the website once we merge the dev branch into master during the next release.

Great job, and thanks for the help! Ping me on Discord if you're interested in working on anything else.

**Comment by salisshuaibu11** [comment]
Should I delete the branch or not, and what's the next thing to do now?

**Pull request merged**
